import React from 'react'
import { styles } from './styles'
import { useNavigate } from 'react-router-dom';

import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';

export default function LandingPage() {

  const mediaQuery = window.matchMedia("(max-width: 550px)");

  const navigate = useNavigate();

  return (
    <>
      <Container maxWidth="xl">
      {mediaQuery.matches?
          <img style={styles.helpImg2} src={require("../../assets/images/help.jpg")} alt="" />:""}
        <Box sx={styles.center}>
          <Box>
            <Typography sx={styles.text1}>Your Technology Partner</Typography>
            <Typography sx={styles.text2}>From strategy to execution</Typography>
            <Typography sx={styles.bodyText}>We see every day as an opportunity to build a great culture and change the way the world works — and it starts with us. At Cosclue, we’re leaders when it comes to employee recognition and engagement. We give employees a voice through pulse surveys, frequent check-ins, and networks that allow them to learn, grow, and contribute to our communities. In fact, it’s our culture and we’re proud of it.
            </Typography>
            <Button variant="contained">About Cosclue</Button>
          </Box>
          {mediaQuery.matches?"":
          <img style={styles.helpImg} src={require("../../assets/images/help.jpg")} alt="" />}
        </Box>
      </Container>
      <Box sx={styles.center}>
        <img style={mediaQuery.matches?styles.rowImg2:styles.rowImg} src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" />
        <img style={mediaQuery.matches?styles.rowImg2:styles.rowImg} src="https://images.unsplash.com/photo-1560264418-c4445382edbc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" />
        {mediaQuery.matches?"":
        <img style={styles.rowImg} src="https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" />
      }
        <img style={mediaQuery.matches?styles.rowImg2:styles.rowImg} src="https://images.unsplash.com/photo-1552581234-26160f608093?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" />
      </Box>
      <Container maxWidth="xl">
      
        <Box sx={styles.center}>
        <Box>
            <Typography sx={styles.text3}>Services</Typography>
            {mediaQuery.matches?
          <img style={styles.helpImg2} src={require("../../assets/images/services.jpg")} alt="" />:""}
            <Typography sx={styles.bodyText}>We are committed to client success. Our clients own the work generated by our world class team.  This allows for the long-term stability of their technology investment. Our goal is simple; to help clients realize their business objectives by delivering professional technology services, including strategic advice, consulting services, data analytics or full-stack software development.</Typography>
            <Button onClick={()=>{navigate("/services")}} variant="contained">Browse All Services</Button>
          </Box>
          {mediaQuery.matches?"":
          <img style={styles.helpImg} src={require("../../assets/images/services.jpg")} alt="" />}
        </Box>
        </Container>
        <Box sx={styles.chatBg}>
            <Typography sx={styles.text3}>Clients</Typography>
            <Typography sx={styles.bodyText}>Our clients are why we exist, and we know that every client is a reference client.</Typography>
            <Button onClick={()=>{navigate("/ourWork")}} variant="contained">Our Work</Button>
        </Box>
        <Container maxWidth="xl">
        <Box sx={styles.center}>
        {mediaQuery.matches?"":
        <img style={styles.helpImg} src={require("../../assets/images/team.jpg")} alt="" />}
          <Box>
            <Typography sx={styles.text3}>Our team = Talent</Typography>
            {mediaQuery.matches?
            <img style={styles.helpImg2} src={require("../../assets/images/team.jpg")} alt="" />:""}
            <Typography sx={styles.bodyText}>Our team is the heartbeat of cosclue, and we are proud to have a collaborative working environment based on knowledge, teamwork and a passion for technology. You can count on our expertise and love of problem solving to set us apart. We thrive on challenges, we work hard, and we get the job done. If you think you’ve got what it takes to be an Cosclueian, we’d love to hear from you.
            </Typography>
            <Button onClick={()=>{navigate("/careers")}} variant="contained">Careers</Button>
          </Box>
        </Box>
      </Container>
      <Box sx={styles.chatBg}>
        <Typography sx={styles.text3}>We would love to hear about your business and technology goals.</Typography>
        <Button onClick={()=>{navigate("/contactUs")}} sx={{mt:"20px"}} variant="contained">Let's Chat</Button>
      </Box>
    </>
  )
}
